name: Build Python Executable for Windows

on:
  push:
    branches: [ "main" ] # Trigger on push to main branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests targeting main
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner for .exe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use latest checkout action

    - name: Set up Python
      uses: actions/setup-python@v5 # Use latest python setup action
      with:
        python-version: '3.10' # Specify Python version (adjust if needed)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller # Install PyInstaller for building

    - name: Build executable with PyInstaller
      run: |
        # --onefile: Bundle everything into a single .exe
        # --windowed: Create a GUI app without a console window
        # --name: Specify the output executable name
        # --icon=path/to/your/icon.ico: (Optional) Add an icon file (e.g., place icon.ico in your repo)
        # main_gui.py: Your main Python script file
        pyinstaller --name ArabicWordExtractor --onefile --windowed main_gui.py
        # Use this if you have data files/folders to include (e.g., icons, models):
        # pyinstaller --name ArabicWordExtractor --onefile --windowed --add-data "path/to/data;data" main_gui.py

    - name: List files in dist directory # For debugging purposes
      run: dir dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # Use latest upload action
      with:
        name: ArabicWordExtractor-Windows # Name of the artifact zip file
        path: dist/ArabicWordExtractor.exe # Path to the built executable

    # Optional: Upload the entire dist directory if needed (e.g., if not using --onefile)
    # - name: Upload dist directory
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ArabicWordExtractor-Windows-Dist
    #     path: dist/
